// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DatabaseInitParameters struct {

	// (String) The engine of the database
	// The engine of the database
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Firewall
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.NamespacedReference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.NamespacedSelector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) Name of the database
	// Name of the database
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the associated network
	// The id of the associated network
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Number) Count of nodes
	// Count of nodes
	Nodes *int64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) The region where the database will be created.
	// The region where the database will be created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the database
	// Size of the database
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The version of the database
	// The version of the database
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DatabaseObservation struct {

	// (String) The DNS endpoint of the database
	// The DNS endpoint of the database
	DNSEndpoint *string `json:"dnsEndpoint,omitempty" tf:"dns_endpoint,omitempty"`

	// (String) The endpoint of the database
	// The endpoint of the database
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (String) The engine of the database
	// The engine of the database
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the database
	// Name of the database
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the associated network
	// The id of the associated network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (Number) Count of nodes
	// Count of nodes
	Nodes *int64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (Number) The port of the database
	// The port of the database
	Port *int64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) The private IP assigned to the database
	// The private IPv4 address for the database
	PrivateIPv4 *string `json:"privateIpv4,omitempty" tf:"private_ipv4,omitempty"`

	// (String) The region where the database will be created.
	// The region where the database will be created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the database
	// Size of the database
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The status of the database
	// The status of the database
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The username of the database
	// The username of the database
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) The version of the database
	// The version of the database
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DatabaseParameters struct {

	// (String) The engine of the database
	// The engine of the database
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Firewall
	// +kubebuilder:validation:Optional
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.NamespacedReference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.NamespacedSelector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) Name of the database
	// Name of the database
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The id of the associated network
	// The id of the associated network
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Number) Count of nodes
	// Count of nodes
	// +kubebuilder:validation:Optional
	Nodes *int64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) The region where the database will be created.
	// The region where the database will be created.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the database
	// Size of the database
	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The version of the database
	// The version of the database
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// DatabaseSpec defines the desired state of Database
type DatabaseSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatabaseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabaseInitParameters `json:"initProvider,omitempty"`
}

// DatabaseStatus defines the observed state of Database.
type DatabaseStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DatabaseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Database is the Schema for the Databases API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engine) || (has(self.initProvider) && has(self.initProvider.engine))",message="spec.forProvider.engine is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodes) || (has(self.initProvider) && has(self.initProvider.nodes))",message="spec.forProvider.nodes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   DatabaseSpec   `json:"spec"`
	Status DatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseList contains a list of Databases
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Database `json:"items"`
}

// Repository type metadata.
var (
	Database_Kind             = "Database"
	Database_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Database_Kind}.String()
	Database_KindAPIVersion   = Database_Kind + "." + CRDGroupVersion.String()
	Database_GroupVersionKind = CRDGroupVersion.WithKind(Database_Kind)
)

func init() {
	SchemeBuilder.Register(&Database{}, &DatabaseList{})
}
