apiVersion: vpc.civo.upbound.io/v1beta1
kind: ReservedIPAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: webserver-www
  name: webserver-www
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: www
    reservedIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: web-server
