apiVersion: dns.civo.upbound.io/v1beta1
kind: Record
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/record
  labels:
    testing.upbound.io/example-name: www
  name: www
spec:
  forProvider:
    domainIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mydomain
    name: www
    ttl: 600
    type: A
    value: ${civo_instance.foo.public_ip}

---

apiVersion: dns.civo.upbound.io/v1beta1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/record
  labels:
    testing.upbound.io/example-name: mydomain
  name: mydomain
spec:
  forProvider:
    name: mydomain.com

---

apiVersion: compute.civo.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/record
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    diskImage: ${element(data.civo_disk_image.debian.diskimages, 0).id}
    hostname: foo.com
    size: ${element(data.civo_instances_size.small.sizes, 0).name}
