// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NetworkInitParameters struct {

	// (String) The CIDR block for the network
	// The CIDR block for the network
	CidrV4 *string `json:"cidrV4,omitempty" tf:"cidr_v4,omitempty"`

	// (String) Name for the network
	// Name for the network
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (List of String) List of nameservers for the network
	// List of nameservers for the network
	NameserversV4 []*string `json:"nameserversV4,omitempty" tf:"nameservers_v4,omitempty"`

	// (String) The region of the network
	// The region of the network
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) End of the IPv4 allocation pool for VLAN
	// End of the IPv4 allocation pool for VLAN
	VlanAllocationPoolV4End *string `json:"vlanAllocationPoolV4End,omitempty" tf:"vlan_allocation_pool_v4_end,omitempty"`

	// (String) Start of the IPv4 allocation pool for VLAN
	// Start of the IPv4 allocation pool for VLAN
	VlanAllocationPoolV4Start *string `json:"vlanAllocationPoolV4Start,omitempty" tf:"vlan_allocation_pool_v4_start,omitempty"`

	// (String) CIDR for VLAN IPv4
	// CIDR for VLAN IPv4
	VlanCidrV4 *string `json:"vlanCidrV4,omitempty" tf:"vlan_cidr_v4,omitempty"`

	// (String) Gateway IP for VLAN IPv4
	// Gateway IP for VLAN IPv4
	VlanGatewayIPV4 *string `json:"vlanGatewayIpV4,omitempty" tf:"vlan_gateway_ip_v4,omitempty"`

	// (Number) VLAN ID for the network
	// VLAN ID for the network
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`

	// (String) Physical interface for VLAN
	// Physical interface for VLAN
	VlanPhysicalInterface *string `json:"vlanPhysicalInterface,omitempty" tf:"vlan_physical_interface,omitempty"`
}

type NetworkObservation struct {

	// (String) The CIDR block for the network
	// The CIDR block for the network
	CidrV4 *string `json:"cidrV4,omitempty" tf:"cidr_v4,omitempty"`

	// (Boolean) If the network is default, this will be true
	// If the network is default, this will be `true`
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name for the network
	// Name for the network
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String) The name of the network
	// The name of the network
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String) List of nameservers for the network
	// List of nameservers for the network
	NameserversV4 []*string `json:"nameserversV4,omitempty" tf:"nameservers_v4,omitempty"`

	// (String) The region of the network
	// The region of the network
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) End of the IPv4 allocation pool for VLAN
	// End of the IPv4 allocation pool for VLAN
	VlanAllocationPoolV4End *string `json:"vlanAllocationPoolV4End,omitempty" tf:"vlan_allocation_pool_v4_end,omitempty"`

	// (String) Start of the IPv4 allocation pool for VLAN
	// Start of the IPv4 allocation pool for VLAN
	VlanAllocationPoolV4Start *string `json:"vlanAllocationPoolV4Start,omitempty" tf:"vlan_allocation_pool_v4_start,omitempty"`

	// (String) CIDR for VLAN IPv4
	// CIDR for VLAN IPv4
	VlanCidrV4 *string `json:"vlanCidrV4,omitempty" tf:"vlan_cidr_v4,omitempty"`

	// (String) Gateway IP for VLAN IPv4
	// Gateway IP for VLAN IPv4
	VlanGatewayIPV4 *string `json:"vlanGatewayIpV4,omitempty" tf:"vlan_gateway_ip_v4,omitempty"`

	// (Number) VLAN ID for the network
	// VLAN ID for the network
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`

	// (String) Physical interface for VLAN
	// Physical interface for VLAN
	VlanPhysicalInterface *string `json:"vlanPhysicalInterface,omitempty" tf:"vlan_physical_interface,omitempty"`
}

type NetworkParameters struct {

	// (String) The CIDR block for the network
	// The CIDR block for the network
	// +kubebuilder:validation:Optional
	CidrV4 *string `json:"cidrV4,omitempty" tf:"cidr_v4,omitempty"`

	// (String) Name for the network
	// Name for the network
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (List of String) List of nameservers for the network
	// List of nameservers for the network
	// +kubebuilder:validation:Optional
	NameserversV4 []*string `json:"nameserversV4,omitempty" tf:"nameservers_v4,omitempty"`

	// (String) The region of the network
	// The region of the network
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) End of the IPv4 allocation pool for VLAN
	// End of the IPv4 allocation pool for VLAN
	// +kubebuilder:validation:Optional
	VlanAllocationPoolV4End *string `json:"vlanAllocationPoolV4End,omitempty" tf:"vlan_allocation_pool_v4_end,omitempty"`

	// (String) Start of the IPv4 allocation pool for VLAN
	// Start of the IPv4 allocation pool for VLAN
	// +kubebuilder:validation:Optional
	VlanAllocationPoolV4Start *string `json:"vlanAllocationPoolV4Start,omitempty" tf:"vlan_allocation_pool_v4_start,omitempty"`

	// (String) CIDR for VLAN IPv4
	// CIDR for VLAN IPv4
	// +kubebuilder:validation:Optional
	VlanCidrV4 *string `json:"vlanCidrV4,omitempty" tf:"vlan_cidr_v4,omitempty"`

	// (String) Gateway IP for VLAN IPv4
	// Gateway IP for VLAN IPv4
	// +kubebuilder:validation:Optional
	VlanGatewayIPV4 *string `json:"vlanGatewayIpV4,omitempty" tf:"vlan_gateway_ip_v4,omitempty"`

	// (Number) VLAN ID for the network
	// VLAN ID for the network
	// +kubebuilder:validation:Optional
	VlanID *int64 `json:"vlanId,omitempty" tf:"vlan_id,omitempty"`

	// (String) Physical interface for VLAN
	// Physical interface for VLAN
	// +kubebuilder:validation:Optional
	VlanPhysicalInterface *string `json:"vlanPhysicalInterface,omitempty" tf:"vlan_physical_interface,omitempty"`
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Network is the Schema for the Networks API. Provides a Civo network resource. This can be used to create, modify, and delete networks.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.label) || (has(self.initProvider) && has(self.initProvider.label))",message="spec.forProvider.label is a required parameter"
	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
