// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ReservedIPInitParameters struct {

	// (String) Name for the ip address
	// Name for the ip address
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region of the ip
	// The region of the ip
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ReservedIPObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The IP Address of the resource
	// The IP Address of the resource
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) Name for the ip address
	// Name for the ip address
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region of the ip
	// The region of the ip
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ReservedIPParameters struct {

	// (String) Name for the ip address
	// Name for the ip address
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region of the ip
	// The region of the ip
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// ReservedIPSpec defines the desired state of ReservedIP
type ReservedIPSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ReservedIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReservedIPInitParameters `json:"initProvider,omitempty"`
}

// ReservedIPStatus defines the observed state of ReservedIP.
type ReservedIPStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ReservedIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReservedIP is the Schema for the ReservedIPs API. Provides a Civo reserved IP to represent a publicly-accessible static IP addresses that can be mapped to one of your Instancesor Load Balancer.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type ReservedIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ReservedIPSpec   `json:"spec"`
	Status ReservedIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReservedIPList contains a list of ReservedIPs
type ReservedIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReservedIP `json:"items"`
}

// Repository type metadata.
var (
	ReservedIP_Kind             = "ReservedIP"
	ReservedIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReservedIP_Kind}.String()
	ReservedIP_KindAPIVersion   = ReservedIP_Kind + "." + CRDGroupVersion.String()
	ReservedIP_GroupVersionKind = CRDGroupVersion.WithKind(ReservedIP_Kind)
)

func init() {
	SchemeBuilder.Register(&ReservedIP{}, &ReservedIPList{})
}
