// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RecordInitParameters struct {

	// (String) ID from domain name
	// ID from domain name
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/dns/v1beta1.Domain
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in dns to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v2.NamespacedReference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in dns to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v2.NamespacedSelector `json:"domainIdSelector,omitempty" tf:"-"`

	// (String) The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	// The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	// Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (Number) How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	// How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) The choice of RR type from a, cname, mx or txt
	// The choice of RR type from a, cname, mx, ns or txt
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	// The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RecordObservation struct {

	// (String) The account ID of this resource
	// The account ID of this resource
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Timestamp when this resource was created
	// Timestamp when this resource was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) ID from domain name
	// ID from domain name
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	// The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	// Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (Number) How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	// How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) The choice of RR type from a, cname, mx or txt
	// The choice of RR type from a, cname, mx, ns or txt
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Timestamp when this resource was updated
	// Timestamp when this resource was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	// The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RecordParameters struct {

	// (String) ID from domain name
	// ID from domain name
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/dns/v1beta1.Domain
	// +kubebuilder:validation:Optional
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in dns to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v2.NamespacedReference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in dns to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v2.NamespacedSelector `json:"domainIdSelector,omitempty" tf:"-"`

	// (String) The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	// The portion before the domain name (e.g. www) or an @ for the apex/root domain (you cannot use an A record with an amex/root domain)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	// Useful for MX records only, the priority mail should be attempted it (defaults to 10)
	// +kubebuilder:validation:Optional
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (Number) How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	// How long caching DNS servers should cache this record for, in seconds (the minimum is 60 and the default if unspecified is 600)
	// +kubebuilder:validation:Optional
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) The choice of RR type from a, cname, mx or txt
	// The choice of RR type from a, cname, mx, ns or txt
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	// The IP address (A or MX), hostname (CNAME or MX) or text value (TXT) to serve for this record
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// RecordSpec defines the desired state of Record
type RecordSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RecordInitParameters `json:"initProvider,omitempty"`
}

// RecordStatus defines the observed state of Record.
type RecordStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Record is the Schema for the Records API. Provides a Civo DNS domain record resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type Record struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ttl) || (has(self.initProvider) && has(self.initProvider.ttl))",message="spec.forProvider.ttl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   RecordSpec   `json:"spec"`
	Status RecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecordList contains a list of Records
type RecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Record `json:"items"`
}

// Repository type metadata.
var (
	Record_Kind             = "Record"
	Record_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Record_Kind}.String()
	Record_KindAPIVersion   = Record_Kind + "." + CRDGroupVersion.String()
	Record_GroupVersionKind = CRDGroupVersion.WithKind(Record_Kind)
)

func init() {
	SchemeBuilder.Register(&Record{}, &RecordList{})
}
