apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/network
  labels:
    testing.upbound.io/example-name: custom_net
  name: custom-net
  namespace: upbound-system
spec:
  forProvider:
    label: test_network
