apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: example-subnet
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    label: example-network
