// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClusterInitParameters struct {

	// sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'. View list of apps on the Civo CLI --> civo kubernetes apps ls
	// Comma separated list of applications to install. Spaces within application names are fine, but shouldn't be either side of the comma. Application names are case-sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'.
	Applications *string `json:"applications,omitempty" tf:"applications,omitempty"`

	// (String) The type of cluster to create, valid options are k3s or talos the default is k3s
	// The type of cluster to create, valid options are `k3s` or `talos` the default is `k3s`
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (String) The cni for the k3s to install (the default is flannel) valid options are cilium or flannel
	// The cni for the k3s to install (the default is `flannel`) valid options are `cilium` or `flannel`
	Cni *string `json:"cni,omitempty" tf:"cni,omitempty"`

	// (String) The existing firewall ID to use for this cluster
	// The existing firewall ID to use for this cluster
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Firewall
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.Reference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.Selector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) The version of k3s to install
	// The version of k3s to install (optional, the default is currently the latest stable available)
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (String) Name for your cluster, must be unique within your account
	// Name for your cluster, must be unique within your account
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network for the cluster, if not declare we use the default one
	// The network for the cluster, if not declare we use the default one
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Number, Deprecated) The number of instances to create
	// The number of instances to create (optional, the default at the time of writing is 3)
	NumTargetNodes *int64 `json:"numTargetNodes,omitempty" tf:"num_target_nodes,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	Pools *PoolsInitParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// (String) The region for the cluster, if not declare we use the region in declared in the provider
	// The region for the cluster, if not declare we use the region in declared in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Space separated list of tags, to be used freely as required
	// Space separated list of tags, to be used freely as required
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String, Deprecated) The size of each node
	// The size of each node (optional, the default is currently g4s.kube.medium)
	TargetNodesSize *string `json:"targetNodesSize,omitempty" tf:"target_nodes_size,omitempty"`

	// The volume type used for the kubernetes nodes
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) (false by default) when set to true, kubeconfig is saved to the provider state file
	// whether to write the kubeconfig to state
	WriteKubeconfig *bool `json:"writeKubeconfig,omitempty" tf:"write_kubeconfig,omitempty"`
}

type ClusterObservation struct {

	// (String) The API server endpoint of the cluster
	// The API server endpoint of the cluster
	APIEndpoint *string `json:"apiEndpoint,omitempty" tf:"api_endpoint,omitempty"`

	// sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'. View list of apps on the Civo CLI --> civo kubernetes apps ls
	// Comma separated list of applications to install. Spaces within application names are fine, but shouldn't be either side of the comma. Application names are case-sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'.
	Applications *string `json:"applications,omitempty" tf:"applications,omitempty"`

	// (String) The type of cluster to create, valid options are k3s or talos the default is k3s
	// The type of cluster to create, valid options are `k3s` or `talos` the default is `k3s`
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (String) The cni for the k3s to install (the default is flannel) valid options are cilium or flannel
	// The cni for the k3s to install (the default is `flannel`) valid options are `cilium` or `flannel`
	Cni *string `json:"cni,omitempty" tf:"cni,omitempty"`

	// (String) The timestamp when the cluster was created
	// The timestamp when the cluster was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The DNS name of the cluster
	// The DNS name of the cluster
	DNSEntry *string `json:"dnsEntry,omitempty" tf:"dns_entry,omitempty"`

	// (String) The existing firewall ID to use for this cluster
	// The existing firewall ID to use for this cluster
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of Object) (see below for nested schema)
	InstalledApplications []InstalledApplicationsObservation `json:"installedApplications,omitempty" tf:"installed_applications,omitempty"`

	// (String) The version of k3s to install
	// The version of k3s to install (optional, the default is currently the latest stable available)
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (String) The IP address of the master node
	// The IP address of the master node
	MasterIP *string `json:"masterIp,omitempty" tf:"master_ip,omitempty"`

	// (String) Name for your cluster, must be unique within your account
	// Name for your cluster, must be unique within your account
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network for the cluster, if not declare we use the default one
	// The network for the cluster, if not declare we use the default one
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (Number, Deprecated) The number of instances to create
	// The number of instances to create (optional, the default at the time of writing is 3)
	NumTargetNodes *int64 `json:"numTargetNodes,omitempty" tf:"num_target_nodes,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	Pools *PoolsObservation `json:"pools,omitempty" tf:"pools,omitempty"`

	// (Boolean) When cluster is ready, this will return true
	// When cluster is ready, this will return `true`
	Ready *bool `json:"ready,omitempty" tf:"ready,omitempty"`

	// (String) The region for the cluster, if not declare we use the region in declared in the provider
	// The region for the cluster, if not declare we use the region in declared in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Status of the cluster
	// Status of the cluster
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Space separated list of tags, to be used freely as required
	// Space separated list of tags, to be used freely as required
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String, Deprecated) The size of each node
	// The size of each node (optional, the default is currently g4s.kube.medium)
	TargetNodesSize *string `json:"targetNodesSize,omitempty" tf:"target_nodes_size,omitempty"`

	// The volume type used for the kubernetes nodes
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) (false by default) when set to true, kubeconfig is saved to the provider state file
	// whether to write the kubeconfig to state
	WriteKubeconfig *bool `json:"writeKubeconfig,omitempty" tf:"write_kubeconfig,omitempty"`
}

type ClusterParameters struct {

	// sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'. View list of apps on the Civo CLI --> civo kubernetes apps ls
	// Comma separated list of applications to install. Spaces within application names are fine, but shouldn't be either side of the comma. Application names are case-sensitive; the available applications can be listed with the Civo CLI: 'civo kubernetes applications ls'. If you want to remove a default installed application, prefix it with a '-', e.g. -Traefik. For application that supports plans, you can use 'app_name:app_plan' format e.g. 'Linkerd:Linkerd & Jaeger' or 'MariaDB:5GB'.
	// +kubebuilder:validation:Optional
	Applications *string `json:"applications,omitempty" tf:"applications,omitempty"`

	// (String) The type of cluster to create, valid options are k3s or talos the default is k3s
	// The type of cluster to create, valid options are `k3s` or `talos` the default is `k3s`
	// +kubebuilder:validation:Optional
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (String) The cni for the k3s to install (the default is flannel) valid options are cilium or flannel
	// The cni for the k3s to install (the default is `flannel`) valid options are `cilium` or `flannel`
	// +kubebuilder:validation:Optional
	Cni *string `json:"cni,omitempty" tf:"cni,omitempty"`

	// (String) The existing firewall ID to use for this cluster
	// The existing firewall ID to use for this cluster
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Firewall
	// +kubebuilder:validation:Optional
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.Reference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.Selector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) The version of k3s to install
	// The version of k3s to install (optional, the default is currently the latest stable available)
	// +kubebuilder:validation:Optional
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (String) Name for your cluster, must be unique within your account
	// Name for your cluster, must be unique within your account
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network for the cluster, if not declare we use the default one
	// The network for the cluster, if not declare we use the default one
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Number, Deprecated) The number of instances to create
	// The number of instances to create (optional, the default at the time of writing is 3)
	// +kubebuilder:validation:Optional
	NumTargetNodes *int64 `json:"numTargetNodes,omitempty" tf:"num_target_nodes,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Pools *PoolsParameters `json:"pools,omitempty" tf:"pools,omitempty"`

	// (String) The region for the cluster, if not declare we use the region in declared in the provider
	// The region for the cluster, if not declare we use the region in declared in the provider
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Space separated list of tags, to be used freely as required
	// Space separated list of tags, to be used freely as required
	// +kubebuilder:validation:Optional
	Tags *string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String, Deprecated) The size of each node
	// The size of each node (optional, the default is currently g4s.kube.medium)
	// +kubebuilder:validation:Optional
	TargetNodesSize *string `json:"targetNodesSize,omitempty" tf:"target_nodes_size,omitempty"`

	// The volume type used for the kubernetes nodes
	// +kubebuilder:validation:Optional
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) (false by default) when set to true, kubeconfig is saved to the provider state file
	// whether to write the kubeconfig to state
	// +kubebuilder:validation:Optional
	WriteKubeconfig *bool `json:"writeKubeconfig,omitempty" tf:"write_kubeconfig,omitempty"`
}

type InstalledApplicationsInitParameters struct {
}

type InstalledApplicationsObservation struct {

	// (String) name of the application
	// Name of application
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// (String) category of the application
	// Category of the application
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// (Boolean) whether application is installed or not
	// Application installation status (`true` if installed)
	Installed *bool `json:"installed,omitempty" tf:"installed,omitempty"`

	// (String) version of the application
	// Version of application
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type InstalledApplicationsParameters struct {
}

type PoolsInitParameters struct {

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	NodeCount *int64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// -> civo kubernetes size
	// Size of the nodes in the nodepool
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	Taint []TaintInitParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type PoolsObservation struct {

	// (List of String) Instance names in the nodepool
	// Instance names in the nodepool
	InstanceNames []*string `json:"instanceNames,omitempty" tf:"instance_names,omitempty"`

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	NodeCount *int64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// -> civo kubernetes size
	// Size of the nodes in the nodepool
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	Taint []TaintObservation `json:"taint,omitempty" tf:"taint,omitempty"`
}

type PoolsParameters struct {

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	// +kubebuilder:validation:Optional
	NodeCount *int64 `json:"nodeCount" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	// +kubebuilder:validation:Optional
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// -> civo kubernetes size
	// Size of the nodes in the nodepool
	// +kubebuilder:validation:Optional
	Size *string `json:"size" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Taint []TaintParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type TaintInitParameters struct {

	// (String)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TaintObservation struct {

	// (String)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TaintParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. Provides a Civo Kubernetes cluster resource. This can be used to create, delete, and modify clusters.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,civo}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pools) || (has(self.initProvider) && has(self.initProvider.pools))",message="spec.forProvider.pools is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
