// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NodePoolInitParameters struct {

	// (String) The ID of your cluster
	// The ID of your cluster
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/kubernetes/v1beta1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	NodeCount *int64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// The region of the cluster the node pool belongs to. Defaults to the account's default region. It scopes every API call made for this resource, because the upstream resource has no region attribute of its own.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the nodes in the nodepool
	// Size of the nodes in the nodepool
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	Taint []NodePoolTaintInitParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NodePoolObservation struct {

	// (String) The ID of your cluster
	// The ID of your cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) Instance names in the nodepool
	// Instance names in the nodepool
	InstanceNames []*string `json:"instanceNames,omitempty" tf:"instance_names,omitempty"`

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	NodeCount *int64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// The region of the cluster the node pool belongs to. Defaults to the account's default region. It scopes every API call made for this resource, because the upstream resource has no region attribute of its own.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the nodes in the nodepool
	// Size of the nodes in the nodepool
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	Taint []NodePoolTaintObservation `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NodePoolParameters struct {

	// (String) The ID of your cluster
	// The ID of your cluster
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/kubernetes/v1beta1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in kubernetes to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Node pool label, if you don't provide one, we will generate one for you
	// Node pool label, if you don't provide one, we will generate one for you
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Map of String)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Number of nodes in the nodepool
	// Number of nodes in the nodepool
	// +kubebuilder:validation:Optional
	NodeCount *int64 `json:"nodeCount,omitempty" tf:"node_count,omitempty"`

	// (Boolean) Node pool belongs to the public ip node pool
	// Node pool belongs to the public ip node pool
	// +kubebuilder:validation:Optional
	PublicIPNodePool *bool `json:"publicIpNodePool,omitempty" tf:"public_ip_node_pool,omitempty"`

	// The region of the cluster the node pool belongs to. Defaults to the account's default region. It scopes every API call made for this resource, because the upstream resource has no region attribute of its own.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Size of the nodes in the nodepool
	// Size of the nodes in the nodepool
	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Taint []NodePoolTaintParameters `json:"taint,omitempty" tf:"taint,omitempty"`
}

type NodePoolTaintInitParameters struct {

	// (String)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NodePoolTaintObservation struct {

	// (String)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NodePoolTaintParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// NodePoolSpec defines the desired state of NodePool
type NodePoolSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NodePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NodePoolInitParameters `json:"initProvider,omitempty"`
}

// NodePoolStatus defines the observed state of NodePool.
type NodePoolStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NodePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NodePool is the Schema for the NodePools API. Provides a Civo Kubernetes node pool resource. While the default node pool must be defined in the civo_kubernetes_cluster resource, this resource can be used to add additional ones to a cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,civo}
type NodePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeCount) || (has(self.initProvider) && has(self.initProvider.nodeCount))",message="spec.forProvider.nodeCount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	Spec   NodePoolSpec   `json:"spec"`
	Status NodePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NodePoolList contains a list of NodePools
type NodePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodePool `json:"items"`
}

// Repository type metadata.
var (
	NodePool_Kind             = "NodePool"
	NodePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NodePool_Kind}.String()
	NodePool_KindAPIVersion   = NodePool_Kind + "." + CRDGroupVersion.String()
	NodePool_GroupVersionKind = CRDGroupVersion.WithKind(NodePool_Kind)
)

func init() {
	SchemeBuilder.Register(&NodePool{}, &NodePoolList{})
}
