// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type InstanceInitParameters struct {

	// (String) The ID for the disk image to use to build the instance
	// The ID for the disk image to use to build the instance
	DiskImage *string `json:"diskImage,omitempty" tf:"disk_image,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Firewall
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.NamespacedReference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.NamespacedSelector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) A fully qualified domain name that should be set as the instance's hostname
	// A fully qualified domain name that should be set as the instance's hostname
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The name of the initial user created on the server
	// The name of the initial user created on the server (optional; this will default to the template's default_username and fallback to civo)
	InitialUser *string `json:"initialUser,omitempty" tf:"initial_user,omitempty"`

	// (String) This must be the ID of the network from the network listing
	// This must be the ID of the network from the network listing (optional; default network used when not specified)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Add some notes to the instance
	// Add some notes to the instance
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// (String) The private IPv4 address for the instance
	// The private IPv4 address for the instance (optional)
	PrivateIPv4 *string `json:"privateIpv4,omitempty" tf:"private_ipv4,omitempty"`

	// (String) This should be either 'none' or 'create' (default: 'create')
	// This should be either 'none' or 'create' (default: 'create')
	PublicIPRequired *string `json:"publicIpRequired,omitempty" tf:"public_ip_required,omitempty"`

	// (String) The region for the instance, if not declare we use the region in declared in the provider
	// The region for the instance, if not declare we use the region in declared in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Can be either the UUID, name, or the IP address of the reserved IP
	// Can be either the UUID, name, or the IP address of the reserved IP
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.ReservedIP
	ReservedIPv4 *string `json:"reservedIpv4,omitempty" tf:"reserved_ipv4,omitempty"`

	// Reference to a ReservedIP in vpc to populate reservedIpv4.
	// +kubebuilder:validation:Optional
	ReservedIPv4Ref *v2.NamespacedReference `json:"reservedIpv4Ref,omitempty" tf:"-"`

	// Selector for a ReservedIP in vpc to populate reservedIpv4.
	// +kubebuilder:validation:Optional
	ReservedIPv4Selector *v2.NamespacedSelector `json:"reservedIpv4Selector,omitempty" tf:"-"`

	// (String) A fully qualified domain name that should be used as the instance's IP's reverse DNS
	// A fully qualified domain name that should be used as the instance's IP's reverse DNS (optional, uses the hostname if unspecified)
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization. To fetch from file: file("${path.module}/script") (this is an immutable field, meaning you can't change it after creation)
	// The contents of a script that will be uploaded to /usr/local/bin/civo-user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization
	Script *string `json:"script,omitempty" tf:"script,omitempty"`

	// (String) The name of the size, from the current list, e.g. g3.xsmall
	// The name of the size, from the current list, e.g. g3.xsmall
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The ID of an already uploaded SSH public key to use for login to the default user
	// The ID of an already uploaded SSH public key to use for login to the default user (optional; if one isn't provided a random password will be set and returned in the initial_password field)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/compute/v1beta1.SSHKey
	SshkeyID *string `json:"sshkeyId,omitempty" tf:"sshkey_id,omitempty"`

	// Reference to a SSHKey in compute to populate sshkeyId.
	// +kubebuilder:validation:Optional
	SshkeyIDRef *v2.NamespacedReference `json:"sshkeyIdRef,omitempty" tf:"-"`

	// Selector for a SSHKey in compute to populate sshkeyId.
	// +kubebuilder:validation:Optional
	SshkeyIDSelector *v2.NamespacedSelector `json:"sshkeyIdSelector,omitempty" tf:"-"`

	// (Set of String) An optional list of tags, represented as a key, value pair
	// An optional list of tags, represented as a key, value pair
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// xfs-2-replicas, px-csi-db (default: csi-s3)
	// The type of volume to use, either 'ssd' or 'bssd' (optional; default 'ssd')
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) if set to true then initial_password for the instance will be saved to provider state file. (default: false)
	// if set to true, initial_password for instance will be saved to provider state file
	WritePassword *bool `json:"writePassword,omitempty" tf:"write_password,omitempty"`
}

type InstanceObservation struct {

	// (Number) Instance's CPU cores
	// Instance's CPU cores
	CPUCores *int64 `json:"cpuCores,omitempty" tf:"cpu_cores,omitempty"`

	// (String) Timestamp when the instance was created
	// Timestamp when the instance was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Number) Instance's disk (GB)
	// Instance's disk (GB)
	DiskGb *int64 `json:"diskGb,omitempty" tf:"disk_gb,omitempty"`

	// (String) The ID for the disk image to use to build the instance
	// The ID for the disk image to use to build the instance
	DiskImage *string `json:"diskImage,omitempty" tf:"disk_image,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// (String) A fully qualified domain name that should be set as the instance's hostname
	// A fully qualified domain name that should be set as the instance's hostname
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the initial user created on the server
	// The name of the initial user created on the server (optional; this will default to the template's default_username and fallback to civo)
	InitialUser *string `json:"initialUser,omitempty" tf:"initial_user,omitempty"`

	// (String) This must be the ID of the network from the network listing
	// This must be the ID of the network from the network listing (optional; default network used when not specified)
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) Add some notes to the instance
	// Add some notes to the instance
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// (String) Instance's private IP address
	// Instance's private IP address
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`

	// (String) The private IPv4 address for the instance
	// The private IPv4 address for the instance (optional)
	PrivateIPv4 *string `json:"privateIpv4,omitempty" tf:"private_ipv4,omitempty"`

	// (String) Instance's public IP address
	// Instance's public IP address
	PublicIP *string `json:"publicIp,omitempty" tf:"public_ip,omitempty"`

	// (String) This should be either 'none' or 'create' (default: 'create')
	// This should be either 'none' or 'create' (default: 'create')
	PublicIPRequired *string `json:"publicIpRequired,omitempty" tf:"public_ip_required,omitempty"`

	// (Number) Instance's RAM (MB)
	// Instance's RAM (MB)
	RAMMb *int64 `json:"ramMb,omitempty" tf:"ram_mb,omitempty"`

	// (String) The region for the instance, if not declare we use the region in declared in the provider
	// The region for the instance, if not declare we use the region in declared in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Can be either the UUID, name, or the IP address of the reserved IP
	// Can be either the UUID, name, or the IP address of the reserved IP
	ReservedIPv4 *string `json:"reservedIpv4,omitempty" tf:"reserved_ipv4,omitempty"`

	// (String) A fully qualified domain name that should be used as the instance's IP's reverse DNS
	// A fully qualified domain name that should be used as the instance's IP's reverse DNS (optional, uses the hostname if unspecified)
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization. To fetch from file: file("${path.module}/script") (this is an immutable field, meaning you can't change it after creation)
	// The contents of a script that will be uploaded to /usr/local/bin/civo-user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization
	Script *string `json:"script,omitempty" tf:"script,omitempty"`

	// (String) The name of the size, from the current list, e.g. g3.xsmall
	// The name of the size, from the current list, e.g. g3.xsmall
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) Instance's source ID
	// Instance's source ID
	SourceID *string `json:"sourceId,omitempty" tf:"source_id,omitempty"`

	// (String) Instance's source type
	// Instance's source type
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// (String) The ID of an already uploaded SSH public key to use for login to the default user
	// The ID of an already uploaded SSH public key to use for login to the default user (optional; if one isn't provided a random password will be set and returned in the initial_password field)
	SshkeyID *string `json:"sshkeyId,omitempty" tf:"sshkey_id,omitempty"`

	// (String) Instance's status
	// Instance's status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Set of String) An optional list of tags, represented as a key, value pair
	// An optional list of tags, represented as a key, value pair
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// xfs-2-replicas, px-csi-db (default: csi-s3)
	// The type of volume to use, either 'ssd' or 'bssd' (optional; default 'ssd')
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) if set to true then initial_password for the instance will be saved to provider state file. (default: false)
	// if set to true, initial_password for instance will be saved to provider state file
	WritePassword *bool `json:"writePassword,omitempty" tf:"write_password,omitempty"`
}

type InstanceParameters struct {

	// (String) The ID for the disk image to use to build the instance
	// The ID for the disk image to use to build the instance
	// +kubebuilder:validation:Optional
	DiskImage *string `json:"diskImage,omitempty" tf:"disk_image,omitempty"`

	// (String) The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// The ID of the firewall to use, from the current list. If left blank or not sent, the default firewall will be used (open to all)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Firewall
	// +kubebuilder:validation:Optional
	FirewallID *string `json:"firewallId,omitempty" tf:"firewall_id,omitempty"`

	// Reference to a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDRef *v2.NamespacedReference `json:"firewallIdRef,omitempty" tf:"-"`

	// Selector for a Firewall in vpc to populate firewallId.
	// +kubebuilder:validation:Optional
	FirewallIDSelector *v2.NamespacedSelector `json:"firewallIdSelector,omitempty" tf:"-"`

	// (String) A fully qualified domain name that should be set as the instance's hostname
	// A fully qualified domain name that should be set as the instance's hostname
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The name of the initial user created on the server
	// The name of the initial user created on the server (optional; this will default to the template's default_username and fallback to civo)
	// +kubebuilder:validation:Optional
	InitialUser *string `json:"initialUser,omitempty" tf:"initial_user,omitempty"`

	// (String) This must be the ID of the network from the network listing
	// This must be the ID of the network from the network listing (optional; default network used when not specified)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) Add some notes to the instance
	// Add some notes to the instance
	// +kubebuilder:validation:Optional
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// (String) The private IPv4 address for the instance
	// The private IPv4 address for the instance (optional)
	// +kubebuilder:validation:Optional
	PrivateIPv4 *string `json:"privateIpv4,omitempty" tf:"private_ipv4,omitempty"`

	// (String) This should be either 'none' or 'create' (default: 'create')
	// This should be either 'none' or 'create' (default: 'create')
	// +kubebuilder:validation:Optional
	PublicIPRequired *string `json:"publicIpRequired,omitempty" tf:"public_ip_required,omitempty"`

	// (String) The region for the instance, if not declare we use the region in declared in the provider
	// The region for the instance, if not declare we use the region in declared in the provider
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Can be either the UUID, name, or the IP address of the reserved IP
	// Can be either the UUID, name, or the IP address of the reserved IP
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/vpc/v1beta1.ReservedIP
	// +kubebuilder:validation:Optional
	ReservedIPv4 *string `json:"reservedIpv4,omitempty" tf:"reserved_ipv4,omitempty"`

	// Reference to a ReservedIP in vpc to populate reservedIpv4.
	// +kubebuilder:validation:Optional
	ReservedIPv4Ref *v2.NamespacedReference `json:"reservedIpv4Ref,omitempty" tf:"-"`

	// Selector for a ReservedIP in vpc to populate reservedIpv4.
	// +kubebuilder:validation:Optional
	ReservedIPv4Selector *v2.NamespacedSelector `json:"reservedIpv4Selector,omitempty" tf:"-"`

	// (String) A fully qualified domain name that should be used as the instance's IP's reverse DNS
	// A fully qualified domain name that should be used as the instance's IP's reverse DNS (optional, uses the hostname if unspecified)
	// +kubebuilder:validation:Optional
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization. To fetch from file: file("${path.module}/script") (this is an immutable field, meaning you can't change it after creation)
	// The contents of a script that will be uploaded to /usr/local/bin/civo-user-init-script on your instance, read/write/executable only by root and then will be executed at the end of the cloud initialization
	// +kubebuilder:validation:Optional
	Script *string `json:"script,omitempty" tf:"script,omitempty"`

	// (String) The name of the size, from the current list, e.g. g3.xsmall
	// The name of the size, from the current list, e.g. g3.xsmall
	// +kubebuilder:validation:Optional
	Size *string `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The ID of an already uploaded SSH public key to use for login to the default user
	// The ID of an already uploaded SSH public key to use for login to the default user (optional; if one isn't provided a random password will be set and returned in the initial_password field)
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/compute/v1beta1.SSHKey
	// +kubebuilder:validation:Optional
	SshkeyID *string `json:"sshkeyId,omitempty" tf:"sshkey_id,omitempty"`

	// Reference to a SSHKey in compute to populate sshkeyId.
	// +kubebuilder:validation:Optional
	SshkeyIDRef *v2.NamespacedReference `json:"sshkeyIdRef,omitempty" tf:"-"`

	// Selector for a SSHKey in compute to populate sshkeyId.
	// +kubebuilder:validation:Optional
	SshkeyIDSelector *v2.NamespacedSelector `json:"sshkeyIdSelector,omitempty" tf:"-"`

	// (Set of String) An optional list of tags, represented as a key, value pair
	// An optional list of tags, represented as a key, value pair
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// xfs-2-replicas, px-csi-db (default: csi-s3)
	// The type of volume to use, either 'ssd' or 'bssd' (optional; default 'ssd')
	// +kubebuilder:validation:Optional
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`

	// (boolean) if set to true then initial_password for the instance will be saved to provider state file. (default: false)
	// if set to true, initial_password for instance will be saved to provider state file
	// +kubebuilder:validation:Optional
	WritePassword *bool `json:"writePassword,omitempty" tf:"write_password,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Provides a Civo instance resource. This can be used to create, modify, and delete instances.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.diskImage) || (has(self.initProvider) && has(self.initProvider.diskImage))",message="spec.forProvider.diskImage is a required parameter"
	Spec   InstanceSpec   `json:"spec"`
	Status InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
