apiVersion: civo.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  # region sets the default Civo region (for example LON1, NYC1, FRA1 or PHX1)
  # for managed resources that do not set their own region.
  # region: LON1
  credentials:
    source: Secret
    secretRef:
      name: civo-creds
      namespace: upbound-system
      key: creds
