// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EgressRuleInitParameters struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +listType=set
	Cidr []*string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type EgressRuleObservation struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +listType=set
	Cidr []*string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) The ID of the firewall rule.
	// The ID of the firewall rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type EgressRuleParameters struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +kubebuilder:validation:Optional
	// +listType=set
	Cidr []*string `json:"cidr" tf:"cidr,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	// +kubebuilder:validation:Optional
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type FirewallInitParameters struct {

	// place (the firewall is never recreated). Changing it to false requires declaring at least one ingress_rule or egress_rule to replace the default rules; changing it back to true is a no-op and does not re-create the default rules.
	// The create rules flag is used to create the default firewall rules, if is not defined will be set to true. This flag only takes effect when the firewall is created; changing it on an existing firewall never recreates the firewall and does not re-create the default rules. If you set it to false you need to define at least one ingress or egress rule
	CreateDefaultRules *bool `json:"createDefaultRules,omitempty" tf:"create_default_rules,omitempty"`

	// (Block Set) The egress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The egress rules, this is a list of rules that will be applied to the firewall
	EgressRule []EgressRuleInitParameters `json:"egressRule,omitempty" tf:"egress_rule,omitempty"`

	// (Block Set) The ingress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The ingress rules, this is a list of rules that will be applied to the firewall
	IngressRule []IngressRuleInitParameters `json:"ingressRule,omitempty" tf:"ingress_rule,omitempty"`

	// (String) The firewall name
	// The firewall name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The firewall network, if is not defined we use the default network
	// The firewall network, if is not defined we use the default network
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) The firewall region, if is not defined we use the global defined in the provider
	// The firewall region, if is not defined we use the global defined in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type FirewallObservation struct {

	// place (the firewall is never recreated). Changing it to false requires declaring at least one ingress_rule or egress_rule to replace the default rules; changing it back to true is a no-op and does not re-create the default rules.
	// The create rules flag is used to create the default firewall rules, if is not defined will be set to true. This flag only takes effect when the firewall is created; changing it on an existing firewall never recreates the firewall and does not re-create the default rules. If you set it to false you need to define at least one ingress or egress rule
	CreateDefaultRules *bool `json:"createDefaultRules,omitempty" tf:"create_default_rules,omitempty"`

	// (Block Set) The egress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The egress rules, this is a list of rules that will be applied to the firewall
	EgressRule []EgressRuleObservation `json:"egressRule,omitempty" tf:"egress_rule,omitempty"`

	// (String) The ID of the firewall rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) The ingress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The ingress rules, this is a list of rules that will be applied to the firewall
	IngressRule []IngressRuleObservation `json:"ingressRule,omitempty" tf:"ingress_rule,omitempty"`

	// (String) The firewall name
	// The firewall name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The firewall network, if is not defined we use the default network
	// The firewall network, if is not defined we use the default network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) The firewall region, if is not defined we use the global defined in the provider
	// The firewall region, if is not defined we use the global defined in the provider
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type FirewallParameters struct {

	// place (the firewall is never recreated). Changing it to false requires declaring at least one ingress_rule or egress_rule to replace the default rules; changing it back to true is a no-op and does not re-create the default rules.
	// The create rules flag is used to create the default firewall rules, if is not defined will be set to true. This flag only takes effect when the firewall is created; changing it on an existing firewall never recreates the firewall and does not re-create the default rules. If you set it to false you need to define at least one ingress or egress rule
	// +kubebuilder:validation:Optional
	CreateDefaultRules *bool `json:"createDefaultRules,omitempty" tf:"create_default_rules,omitempty"`

	// (Block Set) The egress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The egress rules, this is a list of rules that will be applied to the firewall
	// +kubebuilder:validation:Optional
	EgressRule []EgressRuleParameters `json:"egressRule,omitempty" tf:"egress_rule,omitempty"`

	// (Block Set) The ingress rules, this is a list of rules that will be applied to the firewall (see below for nested schema)
	// The ingress rules, this is a list of rules that will be applied to the firewall
	// +kubebuilder:validation:Optional
	IngressRule []IngressRuleParameters `json:"ingressRule,omitempty" tf:"ingress_rule,omitempty"`

	// (String) The firewall name
	// The firewall name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The firewall network, if is not defined we use the default network
	// The firewall network, if is not defined we use the default network
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) The firewall region, if is not defined we use the global defined in the provider
	// The firewall region, if is not defined we use the global defined in the provider
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IngressRuleInitParameters struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +listType=set
	Cidr []*string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type IngressRuleObservation struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +listType=set
	Cidr []*string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// (String) The ID of the firewall rule.
	// The ID of the firewall rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type IngressRuleParameters struct {

	// (String) The action of the rule can be allow or deny. When we set the action = 'allow', this is going to add a rule to allow traffic. Similarly, setting action = 'deny' will deny the traffic.
	// The action of the rule can be allow or deny. When we set the `action = 'allow'`, this is going to add a rule to allow traffic. Similarly, setting `action = 'deny'` will deny the traffic.
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// (Set of String) The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// The CIDR notation of the other end to affect, or a valid network CIDR (e.g. 0.0.0.0/0 to open for everyone or 1.2.3.4/32 to open just for a specific IP address)
	// +kubebuilder:validation:Optional
	// +listType=set
	Cidr []*string `json:"cidr" tf:"cidr,omitempty"`

	// (String) A string that will be the displayed name/reference for this rule
	// A string that will be the displayed name/reference for this rule
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// ), e.g. 80 or 80-443
	// The port or port range to open, can be a single port or a range separated by a dash (`-`), e.g. `80` or `80-443`
	// +kubebuilder:validation:Optional
	PortRange *string `json:"portRange,omitempty" tf:"port_range,omitempty"`

	// (String) The protocol choice from tcp, udp or icmp (the default if unspecified is tcp)
	// The protocol choice from `tcp`, `udp` or `icmp` (the default if unspecified is `tcp`)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

// FirewallSpec defines the desired state of Firewall
type FirewallSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FirewallParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallInitParameters `json:"initProvider,omitempty"`
}

// FirewallStatus defines the observed state of Firewall.
type FirewallStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Firewall is the Schema for the Firewalls API. Provides a Civo firewall resource. This can be used to create, modify, and delete firewalls.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,civo}
type Firewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FirewallSpec   `json:"spec"`
	Status FirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallList contains a list of Firewalls
type FirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Firewall `json:"items"`
}

// Repository type metadata.
var (
	Firewall_Kind             = "Firewall"
	Firewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Firewall_Kind}.String()
	Firewall_KindAPIVersion   = Firewall_Kind + "." + CRDGroupVersion.String()
	Firewall_GroupVersionKind = CRDGroupVersion.WithKind(Firewall_Kind)
)

func init() {
	SchemeBuilder.Register(&Firewall{}, &FirewallList{})
}
