// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *Firewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Network) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReservedIP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReservedIPAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}
