// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ReservedIPAssignmentInitParameters struct {

	// (String) The instance id
	// The instance id
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/compute/v1beta1.Instance
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) The region of the ip
	// The region of the ip
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The reserved ip id
	// The reserved ip id
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.ReservedIP
	ReservedIPID *string `json:"reservedIpId,omitempty" tf:"reserved_ip_id,omitempty"`

	// Reference to a ReservedIP in vpc to populate reservedIpId.
	// +kubebuilder:validation:Optional
	ReservedIPIDRef *v2.Reference `json:"reservedIpIdRef,omitempty" tf:"-"`

	// Selector for a ReservedIP in vpc to populate reservedIpId.
	// +kubebuilder:validation:Optional
	ReservedIPIDSelector *v2.Selector `json:"reservedIpIdSelector,omitempty" tf:"-"`
}

type ReservedIPAssignmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The instance id
	// The instance id
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (String) The region of the ip
	// The region of the ip
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The reserved ip id
	// The reserved ip id
	ReservedIPID *string `json:"reservedIpId,omitempty" tf:"reserved_ip_id,omitempty"`
}

type ReservedIPAssignmentParameters struct {

	// (String) The instance id
	// The instance id
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/compute/v1beta1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) The region of the ip
	// The region of the ip
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The reserved ip id
	// The reserved ip id
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.ReservedIP
	// +kubebuilder:validation:Optional
	ReservedIPID *string `json:"reservedIpId,omitempty" tf:"reserved_ip_id,omitempty"`

	// Reference to a ReservedIP in vpc to populate reservedIpId.
	// +kubebuilder:validation:Optional
	ReservedIPIDRef *v2.Reference `json:"reservedIpIdRef,omitempty" tf:"-"`

	// Selector for a ReservedIP in vpc to populate reservedIpId.
	// +kubebuilder:validation:Optional
	ReservedIPIDSelector *v2.Selector `json:"reservedIpIdSelector,omitempty" tf:"-"`
}

// ReservedIPAssignmentSpec defines the desired state of ReservedIPAssignment
type ReservedIPAssignmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ReservedIPAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReservedIPAssignmentInitParameters `json:"initProvider,omitempty"`
}

// ReservedIPAssignmentStatus defines the observed state of ReservedIPAssignment.
type ReservedIPAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ReservedIPAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReservedIPAssignment is the Schema for the ReservedIPAssignments API. The instance reserved ip assignment resource schema definition
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,civo}
type ReservedIPAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReservedIPAssignmentSpec   `json:"spec"`
	Status            ReservedIPAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReservedIPAssignmentList contains a list of ReservedIPAssignments
type ReservedIPAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReservedIPAssignment `json:"items"`
}

// Repository type metadata.
var (
	ReservedIPAssignment_Kind             = "ReservedIPAssignment"
	ReservedIPAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReservedIPAssignment_Kind}.String()
	ReservedIPAssignment_KindAPIVersion   = ReservedIPAssignment_Kind + "." + CRDGroupVersion.String()
	ReservedIPAssignment_GroupVersionKind = CRDGroupVersion.WithKind(ReservedIPAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&ReservedIPAssignment{}, &ReservedIPAssignmentList{})
}
