apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/network
  labels:
    testing.upbound.io/example-name: example-network
  name: example-network
  namespace: upbound-system
spec:
  forProvider:
    label: example-network
    region: ${data.civo_default_region}
