apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: ReservedIPAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: example-reservedipassignment
  name: example-reservedipassignment
  namespace: upbound-system
spec:
  forProvider:
    region: ${data.civo_default_region}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reservedipassignment
    reservedIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reservedipassignment

---

apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: ReservedIP
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: example-reservedipassignment
  name: example-reservedipassignment
  namespace: upbound-system
spec:
  forProvider:
    name: example-reservedipassignment
    region: ${data.civo_default_region}

---

apiVersion: compute.civo.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: example-reservedipassignment
  name: example-reservedipassignment
  namespace: upbound-system
spec:
  forProvider:
    hostname: example-reservedipassignment
    size: g4s.xsmall
    diskImage: ${data.civo_disk_image_id}
    region: ${data.civo_default_region}
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reservedipassignment
    firewallIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reservedipassignment

---

apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: example-reservedipassignment
  name: example-reservedipassignment
  namespace: upbound-system
spec:
  forProvider:
    label: example-reservedipassignment
    region: ${data.civo_default_region}

---

apiVersion: vpc.civo.m.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/reservedipassignment
  labels:
    testing.upbound.io/example-name: example-reservedipassignment
  name: example-reservedipassignment
  namespace: upbound-system
spec:
  forProvider:
    name: example-reservedipassignment
    region: ${data.civo_default_region}
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reservedipassignment
    createDefaultRules: true
