apiVersion: dns.civo.upbound.io/v1beta1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/domain
  labels:
    testing.upbound.io/example-name: example-domain
  name: example-domain
spec:
  forProvider:
    name: ${Rand.RFC1123Subdomain}.example
