// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ObjectStoreCredentialInitParameters struct {

	// (String) The access key id of the Object Store Credential. It is generated by the provider.
	// The access key id of the Object Store Credential. It is generated by the provider.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// (String) The name of the Object Store Credential. Must be unique.
	// The name of the Object Store Credential. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region where the Object Store Credential will be created.
	// The region where the Object Store Credential will be created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The secret access key of the Object Store Credential. It is generated by the provider.
	// The secret access key of the Object Store Credential. It is generated by the provider.
	SecretAccessKeySecretRef *v2.LocalSecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

type ObjectStoreCredentialObservation struct {

	// (String) The access key id of the Object Store Credential. It is generated by the provider.
	// The access key id of the Object Store Credential. It is generated by the provider.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the Object Store Credential. Must be unique.
	// The name of the Object Store Credential. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region where the Object Store Credential will be created.
	// The region where the Object Store Credential will be created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The status of the Object Store Credential.
	// The status of the Object Store Credential.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ObjectStoreCredentialParameters struct {

	// (String) The access key id of the Object Store Credential. It is generated by the provider.
	// The access key id of the Object Store Credential. It is generated by the provider.
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// (String) The name of the Object Store Credential. Must be unique.
	// The name of the Object Store Credential. Must be unique.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region where the Object Store Credential will be created.
	// The region where the Object Store Credential will be created.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The secret access key of the Object Store Credential. It is generated by the provider.
	// The secret access key of the Object Store Credential. It is generated by the provider.
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v2.LocalSecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

// ObjectStoreCredentialSpec defines the desired state of ObjectStoreCredential
type ObjectStoreCredentialSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectStoreCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectStoreCredentialInitParameters `json:"initProvider,omitempty"`
}

// ObjectStoreCredentialStatus defines the observed state of ObjectStoreCredential.
type ObjectStoreCredentialStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ObjectStoreCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectStoreCredential is the Schema for the ObjectStoreCredentials API. Provides an Object Store Credential resource. This can be used to create, modify, and delete object stores credential.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type ObjectStoreCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ObjectStoreCredentialSpec   `json:"spec"`
	Status ObjectStoreCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectStoreCredentialList contains a list of ObjectStoreCredentials
type ObjectStoreCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectStoreCredential `json:"items"`
}

// Repository type metadata.
var (
	ObjectStoreCredential_Kind             = "ObjectStoreCredential"
	ObjectStoreCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectStoreCredential_Kind}.String()
	ObjectStoreCredential_KindAPIVersion   = ObjectStoreCredential_Kind + "." + CRDGroupVersion.String()
	ObjectStoreCredential_GroupVersionKind = CRDGroupVersion.WithKind(ObjectStoreCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectStoreCredential{}, &ObjectStoreCredentialList{})
}
