// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ObjectStoreInitParameters struct {

	// (String) The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	// The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/storage/v1beta1.ObjectStoreCredential
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("access_key_id",true)
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// Reference to a ObjectStoreCredential in storage to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDRef *v2.NamespacedReference `json:"accessKeyIdRef,omitempty" tf:"-"`

	// Selector for a ObjectStoreCredential in storage to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDSelector *v2.NamespacedSelector `json:"accessKeyIdSelector,omitempty" tf:"-"`

	// (Number) The maximum size of the Object Store. Default is 500GB.
	// The maximum size of the Object Store. Default is 500GB.
	MaxSizeGb *int64 `json:"maxSizeGb,omitempty" tf:"max_size_gb,omitempty"`

	// (String) The name of the Object Store. Must be unique.
	// The name of the Object Store. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	// The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ObjectStoreObservation struct {

	// (String) The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	// The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// (String) The endpoint of the Object Store. It is generated by the provider.
	// The endpoint of the Object Store. It is generated by the provider.
	BucketURL *string `json:"bucketUrl,omitempty" tf:"bucket_url,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The maximum size of the Object Store. Default is 500GB.
	// The maximum size of the Object Store. Default is 500GB.
	MaxSizeGb *int64 `json:"maxSizeGb,omitempty" tf:"max_size_gb,omitempty"`

	// (String) The name of the Object Store. Must be unique.
	// The name of the Object Store. Must be unique.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	// The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The status of the Object Store.
	// The status of the Object Store.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ObjectStoreParameters struct {

	// (String) The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	// The access key ID from the Object Store credential. If this is not set, a new credential will be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/storage/v1beta1.ObjectStoreCredential
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("access_key_id",true)
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// Reference to a ObjectStoreCredential in storage to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDRef *v2.NamespacedReference `json:"accessKeyIdRef,omitempty" tf:"-"`

	// Selector for a ObjectStoreCredential in storage to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDSelector *v2.NamespacedSelector `json:"accessKeyIdSelector,omitempty" tf:"-"`

	// (Number) The maximum size of the Object Store. Default is 500GB.
	// The maximum size of the Object Store. Default is 500GB.
	// +kubebuilder:validation:Optional
	MaxSizeGb *int64 `json:"maxSizeGb,omitempty" tf:"max_size_gb,omitempty"`

	// (String) The name of the Object Store. Must be unique.
	// The name of the Object Store. Must be unique.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	// The region for the Object Store, if not declared we use the region as declared in the provider (Defaults to LON1)
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// ObjectStoreSpec defines the desired state of ObjectStore
type ObjectStoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectStoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectStoreInitParameters `json:"initProvider,omitempty"`
}

// ObjectStoreStatus defines the observed state of ObjectStore.
type ObjectStoreStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ObjectStoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectStore is the Schema for the ObjectStores API. Provides an Object Store resource. This can be used to create, modify, and delete object stores.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type ObjectStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ObjectStoreSpec   `json:"spec"`
	Status ObjectStoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectStoreList contains a list of ObjectStores
type ObjectStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectStore `json:"items"`
}

// Repository type metadata.
var (
	ObjectStore_Kind             = "ObjectStore"
	ObjectStore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectStore_Kind}.String()
	ObjectStore_KindAPIVersion   = ObjectStore_Kind + "." + CRDGroupVersion.String()
	ObjectStore_GroupVersionKind = CRDGroupVersion.WithKind(ObjectStore_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectStore{}, &ObjectStoreList{})
}
