// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VolumeAttachmentInitParameters struct {

	// Whether to attach the instance to the volume at boot
	AttachAtBoot *bool `json:"attachAtBoot,omitempty" tf:"attach_at_boot,omitempty"`

	// (String) The ID of target instance for attachment
	// The ID of target instance for attachment
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/compute/v1beta1.Instance
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) The region for the volume attachment
	// The region for the volume attachment
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of target volume for attachment
	// The ID of target volume for attachment
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/storage/v1beta1.Volume
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`

	// Reference to a Volume in storage to populate volumeId.
	// +kubebuilder:validation:Optional
	VolumeIDRef *v2.NamespacedReference `json:"volumeIdRef,omitempty" tf:"-"`

	// Selector for a Volume in storage to populate volumeId.
	// +kubebuilder:validation:Optional
	VolumeIDSelector *v2.NamespacedSelector `json:"volumeIdSelector,omitempty" tf:"-"`
}

type VolumeAttachmentObservation struct {

	// Whether to attach the instance to the volume at boot
	AttachAtBoot *bool `json:"attachAtBoot,omitempty" tf:"attach_at_boot,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of target instance for attachment
	// The ID of target instance for attachment
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (String) The region for the volume attachment
	// The region for the volume attachment
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of target volume for attachment
	// The ID of target volume for attachment
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type VolumeAttachmentParameters struct {

	// Whether to attach the instance to the volume at boot
	// +kubebuilder:validation:Optional
	AttachAtBoot *bool `json:"attachAtBoot,omitempty" tf:"attach_at_boot,omitempty"`

	// (String) The ID of target instance for attachment
	// The ID of target instance for attachment
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/compute/v1beta1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) The region for the volume attachment
	// The region for the volume attachment
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of target volume for attachment
	// The ID of target volume for attachment
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/namespaced/storage/v1beta1.Volume
	// +kubebuilder:validation:Optional
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`

	// Reference to a Volume in storage to populate volumeId.
	// +kubebuilder:validation:Optional
	VolumeIDRef *v2.NamespacedReference `json:"volumeIdRef,omitempty" tf:"-"`

	// Selector for a Volume in storage to populate volumeId.
	// +kubebuilder:validation:Optional
	VolumeIDSelector *v2.NamespacedSelector `json:"volumeIdSelector,omitempty" tf:"-"`
}

// VolumeAttachmentSpec defines the desired state of VolumeAttachment
type VolumeAttachmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VolumeAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VolumeAttachmentInitParameters `json:"initProvider,omitempty"`
}

// VolumeAttachmentStatus defines the observed state of VolumeAttachment.
type VolumeAttachmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VolumeAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VolumeAttachment is the Schema for the VolumeAttachments API. Manages volume attachment/detachment to an instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,civo}
type VolumeAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VolumeAttachmentSpec   `json:"spec"`
	Status            VolumeAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VolumeAttachmentList contains a list of VolumeAttachments
type VolumeAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VolumeAttachment `json:"items"`
}

// Repository type metadata.
var (
	VolumeAttachment_Kind             = "VolumeAttachment"
	VolumeAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VolumeAttachment_Kind}.String()
	VolumeAttachment_KindAPIVersion   = VolumeAttachment_Kind + "." + CRDGroupVersion.String()
	VolumeAttachment_GroupVersionKind = CRDGroupVersion.WithKind(VolumeAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&VolumeAttachment{}, &VolumeAttachmentList{})
}
