// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VolumeInitParameters struct {

	// (String) A name that you wish to use to refer to this volume
	// A name that you wish to use to refer to this volume
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network that the volume belongs to
	// The network that the volume belongs to
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) The region for the volume, if not declare we use the region in declared in the provider.
	// The region for the volume, if not declare we use the region in declared in the provider.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Number) A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	// A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	SizeGb *int64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// The type of the volume
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type VolumeObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The mount point of the volume (from instance's perspective)
	// The mount point of the volume (from instance's perspective)
	MountPoint *string `json:"mountPoint,omitempty" tf:"mount_point,omitempty"`

	// (String) A name that you wish to use to refer to this volume
	// A name that you wish to use to refer to this volume
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network that the volume belongs to
	// The network that the volume belongs to
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) The region for the volume, if not declare we use the region in declared in the provider.
	// The region for the volume, if not declare we use the region in declared in the provider.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Number) A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	// A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	SizeGb *int64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// The type of the volume
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type VolumeParameters struct {

	// (String) A name that you wish to use to refer to this volume
	// A name that you wish to use to refer to this volume
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network that the volume belongs to
	// The network that the volume belongs to
	// +crossplane:generate:reference:type=github.com/upbound/provider-civo/apis/cluster/vpc/v1beta1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v2.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v2.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) The region for the volume, if not declare we use the region in declared in the provider.
	// The region for the volume, if not declare we use the region in declared in the provider.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Number) A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	// A minimum of 1 and a maximum of your available disk space from your quota specifies the size of the volume in gigabytes
	// +kubebuilder:validation:Optional
	SizeGb *int64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// The type of the volume
	// +kubebuilder:validation:Optional
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

// VolumeSpec defines the desired state of Volume
type VolumeSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   VolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VolumeInitParameters `json:"initProvider,omitempty"`
}

// VolumeStatus defines the observed state of Volume.
type VolumeStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Volume is the Schema for the Volumes API. Provides a Civo volume which can be attached to an instance in order to provide expanded storage.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,civo}
type Volume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sizeGb) || (has(self.initProvider) && has(self.initProvider.sizeGb))",message="spec.forProvider.sizeGb is a required parameter"
	Spec   VolumeSpec   `json:"spec"`
	Status VolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VolumeList contains a list of Volumes
type VolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Volume `json:"items"`
}

// Repository type metadata.
var (
	Volume_Kind             = "Volume"
	Volume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Volume_Kind}.String()
	Volume_KindAPIVersion   = Volume_Kind + "." + CRDGroupVersion.String()
	Volume_GroupVersionKind = CRDGroupVersion.WithKind(Volume_Kind)
)

func init() {
	SchemeBuilder.Register(&Volume{}, &VolumeList{})
}
