apiVersion: storage.civo.m.upbound.io/v1beta1
kind: ObjectStoreCredential
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectstorecredential
  labels:
    testing.upbound.io/example-name: backup
  name: backup
  namespace: upbound-system
spec:
  forProvider:
    accessKeyId: my-access-key
    name: backup-server
    secretAccessKeySecretRef:
      key: example-key
      name: example-secret

---

apiVersion: storage.civo.m.upbound.io/v1beta1
kind: ObjectStore
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectstorecredential
  labels:
    testing.upbound.io/example-name: backup
  name: backup
  namespace: upbound-system
spec:
  forProvider:
    accessKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: backup
    maxSizeGb: 500
    name: backup-server
    region: LON1
